version: '3.8'
services:
  db: 
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web: 
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    # volumes:
    #   - .:/moose-app
    ports: 
      - "3000:3000"
    depends_on:
      - db
    
