@domain = http://localhost:3000


### Tasks Index

GET {{ domain }}/tasks

### Tasks Show 

GET {{ domain }}/tasks/4

### Histories Index

GET {{ domain }}/histories

### Task History

GET {{ domain }}/tasks/3/histories

### Task Create

POST {{ domain }}/tasks
Content-Type: application/json

{
  "name": "Enema",
  "doses_required": 10,
  "doses_given": 9
}

### Task Update

PATCH {{ domain }}/tasks/3
Content-Type: application/json

{
  "doses_given": 3
}

### Task Delete

DELETE {{ domain }}/tasks/5

### Histories create

POST {{ domain }}/histories
Content-Type: application/json

{
  "task_id": 2,
  "all_tasks_completed": false
}

### Histories delete
### DEPRECATED
###DELETE {{ domain }}/tasks/3/histories
 
### Add Dose

GET {{ domain }}/tasks/3/add_dose
Content-Type: application/json


### Reomve Dose

DELETE {{domain}}/tasks/3/remove_dose

